# -*- coding: utf-8 -*-
"""candidate elimination.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cbwaDO92KZnJ8omLVvZxAu3_6nV3HWmH
"""

import numpy as np
import pandas as pd

data = pd.read_csv('enjoysport.csv')

concepts = np.array(data.iloc[:, 0:-1])
target = np.array(data.iloc[:, -1])

def learn(concepts, target):
    s = concepts[0].copy()
    g = [["?"] * len(s) for _ in range(len(s))]

    for i, h in enumerate(concepts):
        if target[i] == 'yes':
            s = [s[x] if h[x] == s[x] else '?' for x in range(len(s))]
        elif target[i] == 'no':
            for x in range(len(s)):
                g[x][x] = '?' if h[x] == s[x] else s[x]

    g = [x for x in g if x != ["?"] * len(s)]
    return s, g

s_final, g_final = learn(concepts, target)

print('Final S: ', s_final, sep="\n")
print('Final G: ', g_final, sep="\n")

data.head()

